name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  release:
    types: [ created ]


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v12
        with:
          repositories: '[{ "id": "github", "name": "DCSA Backend repo", "url": "https://maven.pkg.github.com/dcsaorg/DCSA-Core", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }]'
          servers: '[{ "id": "github", "username": "${{ secrets.DCSA_USER }}", "password": "${{ secrets.DCSA_PACKAGES_PAT }}" }]'

      - name: Get changelist from pom.xml
        id: get-changelist
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'pom.xml'
          xpath: '//*[local-name()="changelist"]'

      - name: Get version from pom.xml
        id: get-version
        run: echo version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT

      - name: Confirm RELEASE Version
        run: |
          IFS='-'
          read -ra PROJ_TAG <<<"${{ steps.get-version.outputs.version }}"

          if [[ "${{ steps.get-changelist.outputs.info }}" == "-RELEASE" &&  "${PROJ_TAG[-1]}" == "RELEASE" ]];
          then
            echo "Version is RELEASE"
          else
            echo "The Version is not RELEASE"
            exit 1
          fi

      - name: maven build
        run: mvn -B package -Dchangelist=-RELEASE


      # Build and push Docker image
      # https://github.com/marketplace/actions/docker-build-push-action
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: dcsa-ui-support
          registry: ghcr.io
          githubOrg: dcsaorg
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          addLatest: ${{ true }}
